# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'DDYYZZBB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DDYYZZBB
   pod 'SnapKit'
   pod 'Alamofire'
  target 'DDYYZZBBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DDYYZZBBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
